name: install-deps

description: 'install node_modules'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-packages-v0-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-packages-v0-
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
      shell: bash
