name: install-deps

description: 'install node_modules'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-packages-v1-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-packages-v1-
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
      shell: bash
