name: code-generate

description: 'code generate'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - uses: actions/cache@v2
      with:
        path: src
        key: api-client-v0-${{ github.sha }}
        restore-keys: |
          api-client-v0-
    - name: code generate
      run: |
        sh scripts/gen-openapi.sh
      shell: bash
