name: build-app

description: 'build app'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      with:
        path: src
        key: api-client-v0-${{ github.sha }}
        restore-keys: |
          api-client-v0-
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-packages-v0-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-packages-v0-
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm run build
      shell: bash
