name: build-app

description: 'build app'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: src
        key: api-client-v0-${{ github.sha }}
        restore-keys: |
          api-client-v0-
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn build
      shell: bash
