name: auto-merge-pr

on: pull_request_target

jobs:
  checkout-api-tag-pr:
    if: github.event.pull_request.opend == true && startsWith(github.event.pull_request.head.ref, 'api_version_tag/v')
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
