name: CI

on:
  - push

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-deps
        uses: ./.github/actions/install-deps
  code-generate:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: code-generate
        uses: ./.github/actions/code-generate
  build-app:
    runs-on: ubuntu-latest
    needs:
      - install-deps
      - code-generate
    steps:
      - uses: actions/checkout@v3
      - name: build-app
        uses: ./.github/actions/build-app
