name: create-checkout-api-tag-pr

on:
  workflow_dispatch:
    inputs:
      api_version_tag:
        required: true

jobs:
  create-checkout-api-tag-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout api tag
        env:
          GIT_TAG: ${{ github.event.inputs.api_version_tag }}
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@@users.noreply.github.com
          BRANCH_NAME: api_version_tag/v${{ github.event.inputs.api_version_tag }}
        run: |
          git config --global user.name "${GIT_AUTHOR_NAME}"
          git config --global user.email "${GIT_AUTHOR_EMAIL}"
          cd submodules/spa_guide_sns_server
          git checkout v${GIT_TAG}
          cd ../
          git add -A && git commit -m "chore: checkout API version v${GIT_TAG}"
          git push -u origin ${BRANCH_NAME}
      - uses: actions/github-script@v3
        env:
          GIT_TAG: ${{ github.event.inputs.api_version_tag }}
          BRANCH_NAME: api_version_tag/v${{ github.event.inputs.api_version_tag }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore: checkout API version v${GIT_TAG}`,
              head: process.env.BRANCH_NAME,
              base: "main",
              body: `Checkout API version v${GIT_TAG}`
            })
      - name: merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --auto
