name: create-version-pr

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  create-version-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: install-deps
        uses: ./.github/actions/install-deps
      - name: Update version
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          NEW_VERSION: ${{ github.event.inputs.version }}
          BRANCH_NAME: version/v${{ github.event.inputs.version }}
        run: |
          git config --global user.email "${GIT_AUTHOR_EMAIL}"
          git config --global user.name "${GIT_AUTHOR_NAME}"
          git switch -c ${BRANCH_NAME}
          yarn version --no-git-tag-version --new-version ${NEW_VERSION}
          git add -A && git commit -m "chore: v${NEW_VERSION}"
          git push -u origin ${BRANCH_NAME}
      - name: Generate changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ github.event.inputs.version }}
        id: generate-changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          $(yarn bin)/lerna-changelog --next-version ${NEW_VERSION} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: actions/github-script@v3
        env:
          NEW_VERSION: ${{ github.event.inputs.version }}
          BRANCH_NAME: version/v${{ github.event.inputs.version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore: v${process.env.NEW_VERSION}`,
              head: process.env.BRANCH_NAME,
              base: "main",
              body: process.env.CHANGELOG
            })
