name: release-npm-package

on:
  release:
    types: [published]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-deps
        uses: ./.github/actions/install-deps
  code-generate:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: code-generate
        uses: ./.github/actions/code-generate
  publish-npm-package:
    runs-on: ubuntu-latest
    needs:
      - code-generate
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: build-package
        uses: ./.github/actions/build-package
      - id: auth
        uses: google-github-actions/auth@v0.8.0
        env:
          GCP_WI_PROVIDER: projects/1091314836174/locations/global/workloadIdentityPools/github-actions-deploy-ar/providers/github-actions
          GCP_SERVICE_ACCOUNT: test-467@web-feature-toggle-sample.iam.gserviceaccount.com
        with:
          workload_identity_provider: ${{ env.GCP_WI_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.1
        env:
          GCP_PROJECT: web-feature-toggle-sample
        with:
          project_id: ${{ env.GCP_PROJECT }}
      - name: upload package
        run: |
          npm run artifactregistry-login
          npm publish
