name: release-npm-package

on:
  create:
    ref-type: tag

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-deps
        uses: ./.github/actions/install-deps
  code-generate:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: code-generate
        uses: ./.github/actions/code-generate
  build-app:
    runs-on: ubuntu-latest
    needs:
      - code-generate
    steps:
      - uses: actions/checkout@v3
      - name: build-app
        uses: ./.github/actions/build-app
  publish-npm-package:
    runs-on: ubuntu-latest
    needs:
      - build-app
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: google-github-actions/auth@v0.6.0
        env:
          GCP_WI_PROVIDER: projects/1091314836174/locations/global/workloadIdentityPools/github-actions-deploy-ar/providers/Github-Actions
          SERVICE_ACCOUNT: test-467@web-feature-toggle-sample.iam.gserviceaccount.com
        with:
          workload_identity_provider: ${{ env.GCP_WI_PROVIDER }}
          service_account: 
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.1
        env:
          GCP_PROJECT: web-feature-toggle-sample
        with:
          project_id: ${{ env.GCP_PROJECT }}
      - name: upload package
        env:
          PUBLISH_REGISTRY: https://asia-northeast1-npm.pkg.dev/web-feature-toggle-sample/spa-guide-js/
        run: |
          yarn artifactregistry-login
          NEW_VERSION=(node -p 'require("./package.json").version')
          yarn publish --non-interactive --new-version=$NEW_VERSION --registry="${PUBLISH_REGISTRY}"
